export const CATS = [
  'Marmitex', 'Prato do dia', 'Prato Feito', 'Massas', 'Omeletes', 'Crepiocas', 'Tapiocas', 
  'Lanches Naturais', 'Lanches Quentes', 'Promoção Lanches Quentes', 'Sucos', 
  'Sucos Detox (Funcionais)', 'Vitaminas', 'Refrigerantes', 'Salgados', 'Sobremesas', 
  'Bomboniere', 'Café', 'Caldos'
];

export const ITEMS = [
  // Marmitex
  {n:'COMBO FEIJOADA',d:'',p:50,c:'Marmitex'},{n:'Marmitex P (1 Carne)',d:'',p:18.9,c:'Marmitex'},{n:'Marmitex P (2 Carne)',d:'',p:23.9,c:'Marmitex'},{n:'Marmitex M (1 Carne)',d:'',p:22.9,c:'Marmitex'},{n:'Marmitex M (2 Carne)',d:'',p:27.9,c:'Marmitex'},{n:'Marmitex Executiva (1 Carne)',d:'',p:27,c:'Marmitex'},{n:'Marmitex Executiva (2 Carne)',d:'',p:30,c:'Marmitex'},{n:'Marmitex M Feijoada',d:'',p:25.9,c:'Marmitex'},
  
  // Lanches Quentes
  {n:'Bauru',d:'Presunto, Muçarela e Tomate.',p:15,c:'Lanches Quentes'},{n:'Misto',d:'Presunto e Mussarela.',p:12,c:'Lanches Quentes'},{n:'Americano',d:'Presunto, Mussarela, Ovo, Alface e Tomate.',p:18,c:'Lanches Quentes'},{n:'X Salada',d:'Hambúrguer, Presunto, Mussarela, Alface e Tomate.',p:18,c:'Lanches Quentes'},{n:'X Salada EGG',d:'',p:19,c:'Lanches Quentes'},{n:'X Salada Bacon',d:'',p:20,c:'Lanches Quentes'},{n:'X Salada EGG Bacon',d:'',p:21,c:'Lanches Quentes'},{n:'X Tudo',d:'',p:22,c:'Lanches Quentes'},{n:'Copa Lombo Salada',d:'',p:20,c:'Lanches Quentes'},{n:'Copa Lombo Salada EGG',d:'',p:21,c:'Lanches Quentes'},{n:'Copa Lombo Salada Bacon',d:'',p:22,c:'Lanches Quentes'},{n:'Copa Lombo Salada Bacon EGG',d:'',p:23,c:'Lanches Quentes'},{n:'Copa Lombo Tudo',d:'',p:25,c:'Lanches Quentes'},{n:'X Linguiça Salada',d:'',p:19,c:'Lanches Quentes'},{n:'X Linguiça Salada EGG',d:'',p:20,c:'Lanches Quentes'},{n:'X Linguiça Bacon',d:'',p:21,c:'Lanches Quentes'},{n:'X Linguiça EGG Bacon',d:'',p:22,c:'Lanches Quentes'},{n:'X Linguiça Tudo',d:'',p:23,c:'Lanches Quentes'},{n:'Frango Salada',d:'',p:21,c:'Lanches Quentes'},{n:'Frango Salada EGG',d:'',p:22,c:'Lanches Quentes'},{n:'Frango Salada Bacon',d:'',p:23,c:'Lanches Quentes'},{n:'Frango Salada EGG Bacon',d:'',p:24,c:'Lanches Quentes'},{n:'Frango Tudo',d:'',p:25,c:'Lanches Quentes'},{n:'Filé Salada',d:'Contra filé, presunto, queijo, alface e tomate.',p:25,c:'Lanches Quentes'},{n:'Filé Salada EGG',d:'',p:27,c:'Lanches Quentes'},{n:'Filé Salada Bacon',d:'',p:29,c:'Lanches Quentes'},{n:'Filé Salada EGG Bacon',d:'',p:31,c:'Lanches Quentes'},{n:'Carne Queijo Acebolado',d:'Contra filé, Queijo, cebola.',p:30,c:'Lanches Quentes'},{n:'Filé tudo',d:'',p:35,c:'Lanches Quentes'},{n:'X Burguer',d:'Hambúrguer e queijo',p:15,c:'Lanches Quentes'},
  
  // Promoção Lanches Quentes
  {n:'Copa Lombo salada',d:'Promoção',p:25,c:'Promoção Lanches Quentes'},{n:'X tudo',d:'Promoção',p:27,c:'Promoção Lanches Quentes'},{n:'X linguiça salada',d:'Promoção',p:24,c:'Promoção Lanches Quentes'},{n:'Frango salada',d:'Promoção',p:26,c:'Promoção Lanches Quentes'},{n:'X salada',d:'Promoção',p:23,c:'Promoção Lanches Quentes'},{n:'2 X tudo',d:'Promoção',p:50,c:'Promoção Lanches Quentes'},
  
  // Salgados (antigos + novos)
  {n:'PF Pão de queijo',d:'',p:3.5,c:'Salgados'},{n:'Croissant de chocolate',d:'',p:8,c:'Salgados'},{n:'Torta de sardinha',d:'',p:7,c:'Salgados'},{n:'Pizzas',d:'',p:8,c:'Salgados'},{n:'Croissant presunto e queijo',d:'',p:8,c:'Salgados'},{n:'Croissant quatro queijos',d:'',p:7,c:'Salgados'},{n:'Croissant frango',d:'',p:8,c:'Salgados'},{n:'Folheado de Ricota',d:'',p:7,c:'Salgados'},{n:'Folheado de peito de peru',d:'',p:7,c:'Salgados'},{n:'Folheado de Presunto e queijo',d:'',p:7,c:'Salgados'},
  {n:'Esfiha de Frango',d:'',p:6,c:'Salgados'},{n:'Esfiha de Carne',d:'',p:6,c:'Salgados'},{n:'Hamburguer (salgado assado)',d:'',p:7,c:'Salgados'},{n:'Doguinho',d:'',p:7,c:'Salgados'},{n:'Enroladinho de presunto e queijo',d:'',p:7,c:'Salgados'},{n:'Pão de Batata Requeijão',d:'',p:6.5,c:'Salgados'},{n:'Pão de Batata Frango',d:'',p:6.5,c:'Salgados'},{n:'Espetinho Frango',d:'',p:7,c:'Salgados'},{n:'Coxinha',d:'',p:6.5,c:'Salgados'},{n:'Enroladinho de salsicha',d:'',p:6.5,c:'Salgados'},{n:'Pastel Carne',d:'',p:6,c:'Salgados'},{n:'Pastel Queijo',d:'',p:6.5,c:'Salgados'},{n:'Quibe frito',d:'',p:6,c:'Salgados'},{n:'Empada Mista',d:'',p:8,c:'Salgados'},{n:'Empada Frango',d:'',p:8,c:'Salgados'},{n:'Empada Palmito',d:'',p:8,c:'Salgados'},{n:'Pizza Calabresa',d:'',p:8,c:'Salgados'},{n:'Pizza Frango',d:'',p:8,c:'Salgados'},{n:'Pizza Presunto e Queijo',d:'',p:8,c:'Salgados'},
  
  // Tapiocas (novas)
  {n:'Escolha sua tapioca doce',d:'',p:25,c:'Tapiocas'},{n:'Tapioca',d:'',p:18,c:'Tapiocas'},
  {n:'Tapioca Creme de Avelã',d:'',p:25,c:'Tapiocas'},{n:'Tapioca Banana com Leite Condensado',d:'',p:25,c:'Tapiocas'},{n:'Tapioca Queijo e Canela',d:'',p:25,c:'Tapiocas'},{n:'Tapioca Romeu & Julieta',d:'',p:25,c:'Tapiocas'},

  // Caldos (novos)
  {n:'Caldo de mandioca',d:'',p:20,c:'Caldos'},
  
  // Sucos
  {n:'Promoção Suco de Limão',d:'',p:9,c:'Sucos'},{n:'Suco 500 ml',d:'',p:12,c:'Sucos'},
  
  // Sobremesas
  {n:'Salada de Frutas',d:'Laranja, mamão, maçã, pera, banana, manga e uva.',p:15,c:'Sobremesas'},{n:'Açaí',d:'',p:18,c:'Sobremesas'},{n:'Pedaço bolo fubá c/laranja',d:'',p:5,c:'Sobremesas'},{n:'Pudim de leite condensado',d:'',p:6,c:'Sobremesas'},
  
  // Café
  {n:'Pão de Queijo',d:'',p:4,c:'Café'},{n:'Pão de Queijo Recheado',d:'',p:6,c:'Café'},{n:'Pão na Chapa com Manteiga',d:'',p:5,c:'Café'},{n:'Pão na chapa com queijo',d:'',p:10,c:'Café'},{n:'Pão com ovo',d:'',p:12,c:'Café'},{n:'Pão com ovo e queijo',d:'',p:15,c:'Café'},{n:'Café',d:'',p:3.5,c:'Café'},{n:'Pingado',d:'',p:7,c:'Café'},{n:'Capuccino Quente',d:'',p:8,c:'Café'},{n:'Capuccino Gelado',d:'',p:10,c:'Café'},
  
  // Refrigerantes
  {n:'Coca cola 1L',d:'Consumo no local',p:10,c:'Refrigerantes'},{n:'Bioleve',d:'',p:4,c:'Refrigerantes'},{n:'Refrigerante lata 350ml',d:'',p:6.5,c:'Refrigerantes'},{n:'Coca cola 220ml',d:'',p:5,c:'Refrigerantes'},{n:'Coca-Cola KS',d:'Consumo no local',p:5,c:'Refrigerantes'},{n:'Coca-Cola 600ml',d:'',p:8,c:'Refrigerantes'},{n:'Coca-Cola 2Lts',d:'',p:13,c:'Refrigerantes'},{n:'Jaboti 600ml',d:'Consumo no local',p:5,c:'Refrigerantes'},{n:'Jaboti 250ml',d:'',p:3.5,c:'Refrigerantes'},{n:'Jaboti 2Lts',d:'',p:7,c:'Refrigerantes'},{n:'Água com Gás',d:'',p:4,c:'Refrigerantes'},{n:'Água sem Gás',d:'',p:4,c:'Refrigerantes'},{n:'Limoneto H2OH',d:'',p:7,c:'Refrigerantes'},{n:'Suco Nativo',d:'',p:3.5,c:'Refrigerantes'},{n:'Guarana Antarctica 300ml (Retornavel)',d:'Consumo no local',p:4.5,c:'Refrigerantes'},
  {n:'Schweppes',d:'',p:7,c:'Refrigerantes'},{n:'Coca cola zero',d:'',p:6.5,c:'Refrigerantes'},{n:'Sprite',d:'',p:6.5,c:'Refrigerantes'},{n:'Fanta Uva',d:'',p:6.5,c:'Refrigerantes'},{n:'Fanta Laranja',d:'',p:6.5,c:'Refrigerantes'},
  
  // Lanches Naturais
  {n:'Lanche Natural',d:'',p:10,c:'Lanches Naturais'},
  
  // Prato do dia
  {n:'PF: File de Frango a Parmegiana',d:'',p:26.9,c:'Prato do dia'},{n:'PF: Quibe assado',d:'',p:20.9,c:'Prato do dia'},{n:'PF: Pernil Suina Acebolada',d:'',p:19.9,c:'Prato do dia'},{n:'Pedaço de quibe',d:'',p:8,c:'Prato do dia'},{n:'PF: Moqueca',d:'',p:26.9,c:'Prato do dia'},{n:'PF: Peixe frito',d:'',p:22.9,c:'Prato do dia'},{n:'Porção de moqueca',d:'',p:20,c:'Prato do dia'},{n:'PF: Fricasse Frango',d:'',p:18.9,c:'Prato do dia'},{n:'PF: Carne de Panela c/ Batata',d:'',p:22.9,c:'Prato do dia'},{n:'PF: Feijão gordo',d:'',p:22.9,c:'Prato do dia'},{n:'PF: Tirinha de Frango Acebolada',d:'',p:18.9,c:'Prato do dia'},{n:'PF : Calabresa Acebolada',d:'',p:18.9,c:'Prato do dia'},{n:'PF: Feijoada',d:'',p:25.9,c:'Prato do dia'},{n:'Pf : Sobrecoxa com Quiabo ao molho',d:'',p:19.9,c:'Prato do dia'},{n:'PF: Copa Lombo em tiras Aceboladas',d:'',p:21.9,c:'Prato do dia'},{n:'PF: Meio d Asa Frango e sobrecoxa refogada suculenta',d:'',p:18.9,c:'Prato do dia'},{n:'Unidade panqueca',d:'',p:10,c:'Prato do dia'},{n:'PF: Carne Suina em cubos',d:'',p:21.9,c:'Prato do dia'},{n:'PF: Almôndega ao molho',d:'',p:20.9,c:'Prato do dia'},{n:'PF: Ponta de Peito de panela',d:'',p:22.9,c:'Prato do dia'},{n:'PF: Costela Bovina cm Mandioca',d:'',p:22.9,c:'Prato do dia'},{n:'PF : Nhoqque c/ Coxinha Asa Frango Frita',d:'',p:22.9,c:'Prato do dia'},{n:'PF : Macarrão ao Sugo c/ Coxinha Frango Frita',d:'',p:20.9,c:'Prato do dia'},{n:'PF: Panqueca',d:'',p:22.9,c:'Prato do dia'},{n:'Unidade charuto',d:'',p:10,c:'Prato do dia'},{n:'PF: Filé de Frango a Milanesa',d:'',p:20.9,c:'Prato do dia'},{n:'PF: Carne Moída c/ Legumes',d:'',p:20.9,c:'Prato do dia'},{n:'PF: Peixe c/ batata ao molho',d:'',p:24.9,c:'Prato do dia'},{n:'PF: Lasanha ao Molho Rose',d:'',p:20.9,c:'Prato do dia'},{n:'PF : Sobrecoxa c/ Macarrão ao Sugo',d:'',p:20.9,c:'Prato do dia'},{n:'Porção de Maionese 300grs',d:'',p:24,c:'Prato do dia'},{n:'PF : Strogonoff de Carne',d:'',p:22.9,c:'Prato do dia'},{n:'PF : Macarrão ao Sugo c/ Sobrecoxa',d:'',p:22.9,c:'Prato do dia'},{n:'Torta de sardinha',d:'',p:7,c:'Prato do dia'},{n:'Capeletti de carne ao molho Bolonhesa',d:'',p:19.9,c:'Prato do dia'},{n:'PF : Nhoqque c/ Sobrecoxa Frango Assada',d:'',p:22.9,c:'Prato do dia'},{n:'PF: Charuto',d:'',p:22.9,c:'Prato do dia'},{n:'PF: Carré Suino Assado c/ Vinagrete',d:'',p:22.9,c:'Prato do dia'},{n:'PF: Tiras de carne Acebolado',d:'',p:22.9,c:'Prato do dia'},{n:'PF : Strogonoff de Frango',d:'',p:19.9,c:'Prato do dia'},{n:'PF: Lasanha ao molho rose presunto e queijo',d:'',p:22.9,c:'Prato do dia'},{n:'PF : Nhoqque c/ Tirinha Carne Acebolada e Salada',d:'',p:22.9,c:'Prato do dia'},{n:'Pedaço individual lasanha',d:'',p:15,c:'Prato do dia'},
  {n:'PF: Bisteca Suina Acebolada',d:'',p:19.9,c:'Prato do dia'},
  
  // Prato Feito
  {n:'PF: Filé de frango',d:'Arroz, feijão, filé de frango grelhado, acompanhamento e salada',p:20.9,c:'Prato Feito'},{n:'PF: Filé de peixe',d:'Arroz, feijão, filé de tilápia grelhado, acompanhamento e salada',p:28.9,c:'Prato Feito'},{n:'PF: Linguiça',d:'Arroz, feijão, linguiça, acompanhamento e salada',p:20.9,c:'Prato Feito'},{n:'PF: sem carne',d:'Arroz, feijão, dois acompanhamentos e salada',p:17.9,c:'Prato Feito'},{n:'Salada no prato',d:'',p:30,c:'Prato Feito'},{n:'PF: Copa Lombo',d:'Arroz, feijão, copa lombo grelhado, acompanhamento e salada',p:21.9,c:'Prato Feito'},{n:'PF: Contra filé',d:'Arroz, feijão, contra filé grelhado, acompanhamento e salada',p:28.9,c:'Prato Feito'},{n:'PF: Kids c/ Nuggets',d:'',p:17.9,c:'Prato Feito'},{n:'PF: Omelete',d:'Omelete simples (sem recheio), Arroz, Feijão e salada',p:16.9,c:'Prato Feito'},{n:'PF: Kids c/ hamburguer',d:'Arroz, feijão, hambúrguer, queijo, batata frita + salada',p:17.9,c:'Prato Feito'},{n:'Add Prato',d:'Somente PDV',p:0,c:'Prato Feito'},
  
  // Bomboniere
  {n:'Azedinha',d:'',p:3,c:'Bomboniere'},{n:'Balas',d:'',p:0.2,c:'Bomboniere'},{n:'Trident',d:'',p:3,c:'Bomboniere'},{n:'Halls',d:'',p:2,c:'Bomboniere'},{n:'Suflair',d:'',p:8,c:'Bomboniere'},{n:'Kit kat',d:'',p:7,c:'Bomboniere'},{n:'Doce Ninho',d:'',p:2.5,c:'Bomboniere'},{n:'Pingo Leite',d:'',p:2.5,c:'Bomboniere'},{n:'Paçoca',d:'',p:3.5,c:'Bomboniere'},{n:'Pé de Moça',d:'',p:3.5,c:'Bomboniere'},{n:'Paçoquita',d:'',p:0.5,c:'Bomboniere'},{n:'Trento',d:'',p:4,c:'Bomboniere'},{n:'Stikadinho',d:'',p:2,c:'Bomboniere'},{n:'Sonho de valsa',d:'',p:2.5,c:'Bomboniere'},{n:'Ouro branco',d:'',p:2.5,c:'Bomboniere'},
  
  // Massas, Omeletes, Crepiocas, Sucos Detox, Vitaminas
  {n:'Nhoque',d:'',p:20,c:'Massas'},
  {n:'Omelete',d:'',p:18,c:'Omeletes'},
  {n:'Crepioca',d:'',p:20,c:'Crepiocas'},
  {n:'Sucos Funcionais (Detox)',d:'',p:15,c:'Sucos Detox (Funcionais)'},
  {n:'Promoção vitamina Mista com Laranja 500 ml',d:'',p:9,c:'Vitaminas'},{n:'Promoção vitamina de Abacate 500ml',d:'',p:10,c:'Vitaminas'},{n:'Vitaminas 500 ml',d:'',p:15,c:'Vitaminas'},
];

export const ADDONS = [
  // Lanche Extras
  {n:'Catupiry', p:3.5, g:'Extras Lanche'},{n:'Cheddar', p:3.5, g:'Extras Lanche'},{n:'Bacon', p:5, g:'Extras Lanche'},{n:'Hambúrger (extra)', p:5, g:'Extras Lanche'},{n:'Ovo', p:3.5, g:'Extras Lanche'},{n:'Presunto (extra)', p:3, g:'Extras Lanche'},{n:'Queijo (extra)', p:5, g:'Extras Lanche'},{n:'Cebola', p:2, g:'Extras Lanche'},{n:'Salsicha', p:3, g:'Extras Lanche'},{n:'Tomate', p:2, g:'Extras Lanche'},{n:'Batata frita (porção)', p:8, g:'Extras Lanche'},
  {n:'Pão Francês (Bola)', p:0, g:'Opções Pão'},{n:'Pão Francês Normal', p:0, g:'Opções Pão'},{n:'Pão de Forma', p:0, g:'Opções Pão'},
  
  // Guarnições Extras (PF)
  {n:'Legumes na manteiga', p:3.5, g:'Guarnições Extras'},{n:'Batata frita', p:5, g:'Guarnições Extras'},{n:'Ovo frito', p:3.5, g:'Guarnições Extras'},{n:'Farofa', p:3.5, g:'Guarnições Extras'},{n:'Macarrão ao Sugo', p:5, g:'Guarnições Extras'},{n:'Polenta frita', p:3.5, g:'Guarnições Extras'},{n:'Purê de batata', p:3.5, g:'Guarnições Extras'},{n:'Couve refogada', p:3.5, g:'Guarnições Extras'},{n:'Mandioca frita', p:3.5, g:'Guarnições Extras'},{n:'Banana frita', p:3.5, g:'Guarnições Extras'},{n:'Abobrinha refogada', p:3.5, g:'Guarnições Extras'},{n:'Batata Gratinada', p:3.5, g:'Guarnições Extras'},{n:'Moranga refogada', p:3.5, g:'Guarnições Extras'},{n:'Maionese', p:3.5, g:'Guarnições Extras'},{n:'Macarrão alho e óleo', p:3.5, g:'Guarnições Extras'},{n:'Creme de Milho', p:3.5, g:'Guarnições Extras'},{n:'Repolho Refogado', p:3.5, g:'Guarnições Extras'},{n:'Beringela/Tomate', p:3.5, g:'Guarnições Extras'},{n:'Arroz', p:3.5, g:'Guarnições Extras'},{n:'Feijão', p:3.5, g:'Guarnições Extras'},{n:'Linguiça', p:7, g:'Guarnições Extras'},{n:'Batata Palha', p:2, g:'Guarnições Extras'},{n:'Torta de frango', p:3.5, g:'Guarnições Extras'},{n:'Mandioca Cozida', p:3.5, g:'Guarnições Extras'},
  {n:'file de peixe', p:12, g:'Proteína Extra'},{n:'Contra filé', p:12, g:'Proteína Extra'},{n:'Filé de frango', p:9, g:'Proteína Extra'},{n:'Copa lombo', p:8, g:'Proteína Extra'},
  
  // Carnes para Marmitex
  {n:'Tirinhas de frango acebolado', p:0, g:'Carnes (Marmitex)'},{n:'Linguiça Acebolada', p:0, g:'Carnes (Marmitex)'},{n:'Calabresa acebolada', p:0, g:'Carnes (Marmitex)'},{n:'Filé de frango', p:0, g:'Carnes (Marmitex)'},{n:'Carne de Panela', p:0, g:'Carnes (Marmitex)'},{n:'Copa lombo', p:0, g:'Carnes (Marmitex)'},{n:'Strogonoff de Frango', p:0, g:'Carnes (Marmitex)'},{n:'Sobre Coxa assada', p:0, g:'Carnes (Marmitex)'},{n:'Panqueca de carne moída', p:0, g:'Carnes (Marmitex)'},{n:'Panqueca de presunto e queijo', p:0, g:'Carnes (Marmitex)'},{n:'Costela Bovina C/ Mandioca', p:0, g:'Carnes (Marmitex)'},{n:'Ponta de Peito na panela', p:0, g:'Carnes (Marmitex)'},{n:'Panqueca de frango', p:0, g:'Carnes (Marmitex)'},{n:'Costelinha Suína', p:0, g:'Carnes (Marmitex)'},{n:'Fricasse de Frango', p:0, g:'Carnes (Marmitex)'},{n:'File Frango Acebolada', p:0, g:'Carnes (Marmitex)'},{n:'Bife Acebolado', p:0, g:'Carnes (Marmitex)'},{n:'Lasanha Abobrinha', p:0, g:'Carnes (Marmitex)'},{n:'Bisteca suina', p:0, g:'Carnes (Marmitex)'},{n:'Bife a Rolê', p:0, g:'Carnes (Marmitex)'},{n:'Peixe frito', p:0, g:'Carnes (Marmitex)'},{n:'Peixe ao molho com batata', p:0, g:'Carnes (Marmitex)'},{n:'Charuto', p:0, g:'Carnes (Marmitex)'},{n:'Lasanha a bolonhesa', p:0, g:'Carnes (Marmitex)'},{n:'Feijão gordo (preto)', p:0, g:'Carnes (Marmitex)'},{n:'Lasanha ao Molho Rose', p:0, g:'Carnes (Marmitex)'},{n:'Meio da asa c/ coxinha refogada', p:0, g:'Carnes (Marmitex)'},{n:'Carne de Panela c/ batata', p:0, g:'Carnes (Marmitex)'},{n:'Filé de Frango a Milanesa', p:0, g:'Carnes (Marmitex)'},{n:'Carne Moida c/ legumes', p:0, g:'Carnes (Marmitex)'},{n:'Almôndega ao molho', p:0, g:'Carnes (Marmitex)'},{n:'Strogonoff de Carne', p:0, g:'Carnes (Marmitex)'},{n:'Nuggets Frito', p:0, g:'Carnes (Marmitex)'},{n:'Carré Suino Assado c/ Vinagrete', p:0, g:'Carnes (Marmitex)'},
  
  // Guarnições base para Marmitex
  {n:'Legumes na Manteiga', p:0, g:'Guarnições (Marmitex)'},{n:'Ovo Frito', p:0, g:'Guarnições (Marmitex)'},{n:'Batata Frita', p:0, g:'Guarnições (Marmitex)'},{n:'Farofa', p:0, g:'Guarnições (Marmitex)'},{n:'Cabutiá refogada', p:0, g:'Guarnições (Marmitex)'},{n:'Repolho refogado', p:0, g:'Guarnições (Marmitex)'},{n:'Batata palha', p:0, g:'Guarnições (Marmitex)'},{n:'Batata sauté', p:0, g:'Guarnições (Marmitex)'},{n:'Beringela refogada', p:0, g:'Guarnições (Marmitex)'},{n:'Couve refogada', p:0, g:'Guarnições (Marmitex)'},{n:'Torta de sardinha', p:0, g:'Guarnições (Marmitex)'},{n:'Maionese', p:0, g:'Guarnições (Marmitex)'},{n:'Polenta frita', p:0, g:'Guarnições (Marmitex)'},{n:'Macarrão ao Sugo', p:0, g:'Guarnições (Marmitex)'},{n:'Macarrão alho e óleo', p:0, g:'Guarnições (Marmitex)'},{n:'Abobrinha refogado', p:0, g:'Guarnições (Marmitex)'},{n:'Macarrão c/ calabresa', p:0, g:'Guarnições (Marmitex)'},{n:'Mandioca frita', p:0, g:'Guarnições (Marmitex)'},{n:'Banana frita', p:0, g:'Guarnições (Marmitex)'},{n:'Batata gratinada', p:0, g:'Guarnições (Marmitex)'},{n:'Purê de batata', p:0, g:'Guarnições (Marmitex)'},{n:'chuchu refogado', p:0, g:'Guarnições (Marmitex)'},{n:'Creme de Milho', p:0, g:'Guarnições (Marmitex)'},
  
  // Sabores Suco (1 grátis)
  {n:'Abacaxi', p:0, g:'Sabores Base Bebida'},{n:'Acerola', p:0, g:'Sabores Base Bebida'},{n:'Amora', p:0, g:'Sabores Base Bebida'},{n:'Cajá', p:0, g:'Sabores Base Bebida'},{n:'Caju', p:0, g:'Sabores Base Bebida'},{n:'Cupuaçu', p:0, g:'Sabores Base Bebida'},{n:'Frutas Vermelhas', p:0, g:'Sabores Base Bebida'},{n:'Goiaba', p:0, g:'Sabores Base Bebida'},{n:'Graviola', p:0, g:'Sabores Base Bebida'},{n:'Laranja', p:0, g:'Sabores Base Bebida'},{n:'Limão', p:0, g:'Sabores Base Bebida'},{n:'Mamão', p:0, g:'Sabores Base Bebida'},{n:'Manga', p:0, g:'Sabores Base Bebida'},{n:'Melancia', p:0, g:'Sabores Base Bebida'},{n:'Melão', p:0, g:'Sabores Base Bebida'},{n:'Morango', p:0, g:'Sabores Base Bebida'},{n:'Pêssego', p:0, g:'Sabores Base Bebida'},{n:'Tamarindo', p:0, g:'Sabores Base Bebida'},{n:'Uva', p:0, g:'Sabores Base Bebida'},{n:'Maracujá', p:0, g:'Sabores Base Bebida'},{n:'Tangerina', p:0, g:'Sabores Base Bebida'},{n:'Açai', p:0, g:'Sabores Base Bebida'},
  
  // Sabores Extra Suco (Pagos)
  {n:'Abacaxi (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Acerola (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Amora (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Cajá (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Caju (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Cupuaçu (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Frutas Vermelhas (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Goiaba (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Graviola (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Laranja (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Limão (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Mamão (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Manga (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Melancia (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Melão (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Morango (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Pêssego (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Tamarindo (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Uva (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Maracujá (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Açai (Extra)', p:3, g:'Sabores Extra Bebida'},{n:'Beterraba e Cenoura', p:3, g:'Sabores Extra Bebida'},
  
  // Personalização Bebida
  {n:'Com açúcar', p:0, g:'Personalização'},{n:'Sem açúcar', p:0, g:'Personalização'},{n:'Com Gelo', p:0, g:'Personalização'},{n:'Sem Gelo', p:0, g:'Personalização'},{n:'Embalagem Copo 500ml', p:0, g:'Personalização'},{n:'Garrafa Embalagem 500ml', p:2, g:'Personalização'},
  {n:'Leite condensado', p:3, g:'Extras Vitamina'},{n:'Gengibre', p:2, g:'Extras Vitamina'},{n:'Chia', p:1, g:'Extras Vitamina'},{n:'Linhaça', p:1, g:'Extras Vitamina'},{n:'Pó de Guaraná', p:1, g:'Extras Vitamina'},
  
  // Toppings Açaí
  {n:'Banana', p:0, g:'Toppings Açaí'},{n:'Granola', p:0, g:'Toppings Açaí'},{n:'Morango', p:0, g:'Toppings Açaí'},{n:'Kiwi', p:0, g:'Toppings Açaí'},{n:'Uva', p:0, g:'Toppings Açaí'},{n:'Leite em Pó', p:0, g:'Toppings Açaí'},{n:'Leite Condensado', p:0, g:'Toppings Açaí'},{n:'Manga', p:0, g:'Toppings Açaí'},{n:'Chocopower Ball', p:5, g:'Toppings Açaí (Pagos)'},{n:'Confete', p:5, g:'Toppings Açaí (Pagos)'},{n:'Nutella', p:5, g:'Toppings Açaí (Pagos)'},

  // Opções de Feijão
  {n:'Com feijão Tradicional', p:0, g:'Opção de Feijão'},{n:'Sem feijão', p:0, g:'Opção de Feijão'},{n:'Feijão Preto c/ Bacon e Calabresa', p:0, g:'Opção de Feijão'},
  
  // Recheio Massas
  {n:'Carne moída', p:0, g:'Recheio Massa'},{n:'Presunto e queijo', p:0, g:'Recheio Massa'},{n:'Frango', p:0, g:'Recheio Massa'},{n:'Mussarela', p:0, g:'Recheio Massa'}
];
