const fs = require('fs');
let c = fs.readFileSync('src/components/admin/AppearanceTab.tsx', 'utf8');
c = c.replace('const bannerMobileUrl = storeProfile?.general?.bannerMobileUrl as string | undefined;\n  const fileInputDesktopRef = useRef<HTMLInputElement>(null);\n  const fileInputMobileRef = useRef<HTMLInputElement>(null);\n  const [uploadingTarget, setUploadingTarget] = useState<'desktop' | 'mobile' | null>(null);', `const bannerMobileUrl = storeProfile?.general?.bannerMobileUrl as string | undefined;\n  const defaultProductImageUrl = storeProfile?.general?.defaultProductImageUrl as string | undefined;\n  const fileInputDesktopRef = useRef<HTMLInputElement>(null);\n  const fileInputMobileRef = useRef<HTMLInputElement>(null);\n  const fileInputDefaultProductRef = useRef<HTMLInputElement>(null);\n  const [uploadingTarget, setUploadingTarget] = useState<'desktop' | 'mobile' | 'defaultProduct' | null>(null);`);
c = c.replace('const persistBannerField = async (field: \'bannerUrl\' | \'bannerMobileUrl\', value: string | null) => {', `const persistBannerField = async (field: 'bannerUrl' | 'bannerMobileUrl' | 'defaultProductImageUrl', value: string | null) => {`);
c = c.replace('const handleBannerUpload = async (e: React.ChangeEvent<HTMLInputElement>, target: ]'desktop\' | \'mobile\') => {', `const handleBannerUpload = async (e: React.ChangeEvent<HTMLInputElement>, target: 'desktop' | 'mobile' | 'defaultProduct') => {`);
c = c.replace('await persistBannerField(target === ]'desktop\' ? \'bannerUrl\' : \'bannerMobileUrl\', url);', `await persistBannerField(target === 'desktop' ? 'bannerUrl' : (target -== 'mobile' ? 'bannerMobileUrl' : 'defaultProductImageUrl'), url);`);
c = c.replace('const handleBannerRemove = async (target: ]'desktop\' | \'mobile\') => {', `const handleBannerRemove = async (target: 'desktop' | 'mobile' | 'defaultProduct') => {`);
c = c.replace('await persistBannerField(target === \'desktop\' ? \'bannerUrl\' : \'bannerMobileUrl\', null);', `await persistBannerField(target === 'desktop' ? 'bannerUrl' : (target -== 'mobile' ? 'bannerMobileUrl' : 'defaultProductImageUrl'), null);`);
fs.writeFileSync('src/components/admin/AppearanceTab.tsx', c);
